// @license
// Copyright The Closure Library Authors.
// SPDX-License-Identifier: Apache-2.0

/**
 * @fileoverview List formatting symbols for all locales.
 *
 * This file is autogenerated by a script.
 * File generated from CLDR ver. 43
 *
 * To reduce the file size (which may cause issues in some JS
 * developing environments), this file will only contain locales
 * that are usually supported by Google products. It is a super
 * set of 40 languages. The rest of the data can be found in another file
 * named "listsymbolsext.js", which will be generated at the same
 * time as this file.
 *
 */

// clang-format off

/**
 * Collection of List formatting symbols symbols for each locale
 *   Each is an array for styles LONG, SHORT, NARROW.
 * @typedef{{
 *   AND_START: !Array<string>,
 *   AND_TWO: (!Array<string>|undefined),
 *   AND_MIDDLE: (!Array<string>|undefined),
 *   AND_END: (!Array<string>|undefined),
 *   OR_START: (!Array<string>|undefined),
 *   OR_TWO: (!Array<string>|undefined),
 *   OR_MIDDLE: (!Array<string>|undefined),
 *   OR_END: (!Array<string>|undefined),
 *   UNIT_START: (!Array<string>|undefined),
 *   UNIT_TWO: (!Array<string>|undefined),
 *   UNIT_MIDDLE: (!Array<string>|undefined),
 *   UNIT_END: (!Array<string>|undefined)
 *  }}
 */
export let ListFormatSymbols;

/**
 * List formatting symbols for locale af.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_af = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} en {1}', '{0} en {1}', '{0} en {1}'],
  AND_END: ['{0} en {1}', '{0} en {1}', '{0}, {1}'],
  OR_TWO: ['{0} of {1}', '{0} of {1}', '{0} of {1}'],
  OR_END: ['{0} of {1}', '{0} of {1}', '{0} of {1}'],
  UNIT_END: ['{0} en {1}', '{0} en {1}', '{0} en {1}']
};

/**
 * List formatting symbols for locale am.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_am = {
  AND_START: ['{0}፣ {1}', '{0}፣ {1}', '{0}, {1}'],
  AND_TWO: ['{0} እና {1}', '{0} እና {1}', '{0} እና {1}'],
  AND_MIDDLE: ['{0}፣ {1}', '{0}፣ {1}', '{0}፣ {1}'],
  AND_END: ['{0}, እና {1}', '{0}, እና {1}', '{0}, እና {1}'],
  OR_START: ['{0}፣ {1}', '{0}፣ {1}', '{0}፣ {1}'],
  OR_TWO: ['{0} ወይም {1}﻿', '{0} ወይም {1}﻿', '{0} ወይም {1}﻿'],
  OR_MIDDLE: ['{0}፣ {1}', '{0}፣ {1}', '{0}፣ {1}'],
  OR_END: ['{0}፣ ወይም {1}', '{0}፣ ወይም {1}', '{0}፣ ወይም {1}'],
  UNIT_START: ['{0}፣ {1}', '{0}፣ {1}', '{0}፣ {1}'],
  UNIT_MIDDLE: ['{0}፣ {1}', '{0}፣ {1}', '{0}፣ {1}'],
  UNIT_END: ['{0}፣ {1}', '{0}፣ {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale ar.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ar = {
  AND_START: ['{0} و{1}', '{0} و{1}', '{0} و{1}'],
  AND_END: ['{0} و{1}', '{0} و{1}', '{0} و{1}'],
  OR_START: ['{0} أو {1}', '{0} أو {1}', '{0} أو {1}'],
  OR_MIDDLE: ['{0} أو {1}', '{0} أو {1}', '{0} أو {1}'],
  OR_END: ['{0} أو {1}', '{0} أو {1}', '{0} أو {1}'],
  UNIT_START: ['{0}، و{1}', '{0}، و{1}', '{0} و{1}'],
  UNIT_TWO: ['{0} و{1}', '{0} و{1}', '{0} و{1}'],
  UNIT_MIDDLE: ['{0}، و{1}', '{0}، و{1}', '{0} و{1}'],
  UNIT_END: ['{0}، و{1}', '{0}، و{1}', '{0} و{1}']
};

/**
 * List formatting symbols for locale ar_DZ.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ar_DZ = {
  AND_START: ['{0} و{1}', '{0} و{1}', '{0} و{1}'],
  AND_END: ['{0} و{1}', '{0} و{1}', '{0} و{1}'],
  OR_START: ['{0} أو {1}', '{0} أو {1}', '{0} أو {1}'],
  OR_MIDDLE: ['{0} أو {1}', '{0} أو {1}', '{0} أو {1}'],
  OR_END: ['{0} أو {1}', '{0} أو {1}', '{0} أو {1}'],
  UNIT_START: ['{0}، و{1}', '{0}، و{1}', '{0} و{1}'],
  UNIT_TWO: ['{0} و{1}', '{0} و{1}', '{0} و{1}'],
  UNIT_MIDDLE: ['{0}، و{1}', '{0}، و{1}', '{0} و{1}'],
  UNIT_END: ['{0}، و{1}', '{0}، و{1}', '{0} و{1}']
};

/**
 * List formatting symbols for locale ar_EG.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ar_EG = {
  AND_START: ['{0} و{1}', '{0} و{1}', '{0} و{1}'],
  AND_END: ['{0} و{1}', '{0} و{1}', '{0} و{1}'],
  OR_START: ['{0} أو {1}', '{0} أو {1}', '{0} أو {1}'],
  OR_MIDDLE: ['{0} أو {1}', '{0} أو {1}', '{0} أو {1}'],
  OR_END: ['{0} أو {1}', '{0} أو {1}', '{0} أو {1}'],
  UNIT_START: ['{0}، و{1}', '{0}، و{1}', '{0} و{1}'],
  UNIT_TWO: ['{0} و{1}', '{0} و{1}', '{0} و{1}'],
  UNIT_MIDDLE: ['{0}، و{1}', '{0}، و{1}', '{0} و{1}'],
  UNIT_END: ['{0}، و{1}', '{0}، و{1}', '{0} و{1}']
};

/**
 * List formatting symbols for locale az.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_az = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} və {1}', '{0} və {1}', '{0}, {1}'],
  OR_END: ['{0}, yaxud {1}', '{0}, yaxud {1}', '{0}, yaxud {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale be.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_be = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} і {1}', '{0} і {1}', '{0} і {1}'],
  OR_END: ['{0} ці {1}', '{0} ці {1}', '{0} ці {1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale bg.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_bg = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} и {1}', '{0} и {1}', '{0}, {1}'],
  AND_END: ['{0} и {1}', '{0} и {1}', '{0} и {1}'],
  OR_TWO: ['{0} или {1}', '{0} или {1}', '{0} или {1}'],
  OR_END: ['{0} или {1}', '{0} или {1}', '{0} или {1}'],
  UNIT_TWO: ['{0} и {1}', '{0} и {1}', '{0} и {1}'],
  UNIT_END: ['{0} и {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale bn.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_bn = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} এবং {1}', '{0} এবং {1}', '{0}, {1}'],
  OR_END: ['{0}, বা {1}', '{0}, বা {1}', '{0}, বা {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale br.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_br = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} ha {1}', '{0} & {1}', '{0} & {1}'],
  OR_END: ['{0} pe {1}', '{0} pe {1}', '{0} pe {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale bs.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_bs = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}'],
  OR_END: ['{0} ili {1}', '{0} ili {1}', '{0} ili {1}'],
  UNIT_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}']
};

/**
 * List formatting symbols for locale ca.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ca = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}'],
  OR_END: ['{0} o {1}', '{0} o {1}', '{0} o {1}'],
  UNIT_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}']
};

/**
 * List formatting symbols for locale chr.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_chr = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} ᎠᎴ {1}', '{0} & {1}', '{0}, {1}'],
  AND_END: ['{0}, ᎠᎴ {1}', '{0}, & {1}', '{0}, & {1}'],
  OR_TWO: ['{0} ᎠᎴᏱᎩ {1}', '{0} ᎠᎴᏱᎩ {1}', '{0} ᎠᎴᏱᎩ {1}'],
  OR_END: ['{0}, ᎠᎴᏱᎩ {1}', '{0}, ᎠᎴᏱᎩ {1}', '{0}, ᎠᎴᏱᎩ {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale cs.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_cs = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} a {1}', '{0} a {1}', '{0}, {1}'],
  OR_END: ['{0} nebo {1}', '{0} nebo {1}', '{0} nebo {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_TWO: ['{0} a {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} a {1}', '{0} a {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale cy.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_cy = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} a(c) {1}', '{0} a(c) {1}', '{0}, {1}'],
  AND_END: ['{0}, a(c) {1}', '{0}, a(c) {1}', '{0}, {1}'],
  OR_TWO: ['{0} neu {1}', '{0} neu {1}', '{0} neu {1}'],
  OR_END: ['{0} neu {1}', '{0} neu {1}', '{0} neu {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale da.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_da = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} og {1}', '{0} og {1}', '{0} og {1}'],
  OR_END: ['{0} eller {1}', '{0} eller {1}', '{0} eller {1}'],
  UNIT_END: ['{0} og {1}', '{0} og {1}', '{0} og {1}']
};

/**
 * List formatting symbols for locale de.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_de = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} und {1}', '{0} und {1}', '{0} und {1}'],
  OR_END: ['{0} oder {1}', '{0} oder {1}', '{0} oder {1}'],
  UNIT_TWO: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  UNIT_END: ['{0} und {1}', '{0} und {1}', '{0} und {1}']
};

/**
 * List formatting symbols for locale de_AT.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_de_AT = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} und {1}', '{0} und {1}', '{0} und {1}'],
  OR_END: ['{0} oder {1}', '{0} oder {1}', '{0} oder {1}'],
  UNIT_TWO: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  UNIT_END: ['{0} und {1}', '{0} und {1}', '{0} und {1}']
};

/**
 * List formatting symbols for locale de_CH.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_de_CH = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} und {1}', '{0} und {1}', '{0} und {1}'],
  OR_END: ['{0} oder {1}', '{0} oder {1}', '{0} oder {1}'],
  UNIT_TWO: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  UNIT_END: ['{0} und {1}', '{0} und {1}', '{0} und {1}']
};

/**
 * List formatting symbols for locale el.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_el = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} και {1}', '{0} και {1}', '{0}, {1}'],
  OR_END: ['{0} ή {1}', '{0} ή {1}', '{0} ή {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale en.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_en = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} and {1}', '{0} & {1}', '{0}, {1}'],
  AND_END: ['{0}, and {1}', '{0}, & {1}', '{0}, {1}'],
  OR_TWO: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  OR_END: ['{0}, or {1}', '{0}, or {1}', '{0}, or {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale en_AU.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_en_AU = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} and {1}', '{0} and {1}', '{0}, {1}'],
  OR_END: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale en_CA.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_en_CA = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} and {1}', '{0} and {1}', '{0}, {1}'],
  OR_END: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale en_GB.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_en_GB = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} and {1}', '{0} and {1}', '{0}, {1}'],
  OR_END: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale en_IE.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_en_IE = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} and {1}', '{0} and {1}', '{0}, {1}'],
  OR_END: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale en_IN.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_en_IN = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} and {1}', '{0} and {1}', '{0}, {1}'],
  AND_END: ['{0} and {1}', '{0} and {1}', '{0}, and {1}'],
  OR_TWO: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  OR_END: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale en_SG.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_en_SG = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} and {1}', '{0} and {1}', '{0}, {1}'],
  OR_END: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale en_US.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_en_US = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} and {1}', '{0} & {1}', '{0}, {1}'],
  AND_END: ['{0}, and {1}', '{0}, & {1}', '{0}, {1}'],
  OR_TWO: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  OR_END: ['{0}, or {1}', '{0}, or {1}', '{0}, or {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale en_ZA.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_en_ZA = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} and {1}', '{0} and {1}', '{0}, {1}'],
  OR_END: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale es.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_es = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} y {1}', '{0} y {1}', '{0} y {1}'],
  OR_END: ['{0} o {1}', '{0} o {1}', '{0} o {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_TWO: ['{0} y {1}', '{0} y {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} y {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale es_419.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_es_419 = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} y {1}', '{0} y {1}', '{0} y {1}'],
  OR_END: ['{0} o {1}', '{0} o {1}', '{0} o {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_TWO: ['{0} y {1}', '{0} y {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} y {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale es_ES.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_es_ES = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} y {1}', '{0} y {1}', '{0} y {1}'],
  OR_END: ['{0} o {1}', '{0} o {1}', '{0} o {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_TWO: ['{0} y {1}', '{0} y {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} y {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale es_MX.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_es_MX = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} y {1}', '{0} y {1}', '{0} y {1}'],
  OR_END: ['{0} o {1}', '{0} o {1}', '{0} o {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_TWO: ['{0} y {1}', '{0} y {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} y {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale es_US.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_es_US = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} y {1}', '{0} y {1}', '{0} y {1}'],
  OR_END: ['{0} o {1}', '{0} o {1}', '{0} o {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} y {1}', '{0} y {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale et.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_et = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} ja {1}', '{0} ja {1}', '{0}, {1}'],
  OR_END: ['{0} või {1}', '{0} või {1}', '{0} või {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale eu.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_eu = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} eta {1}', '{0} eta {1}', '{0}, {1}'],
  OR_END: ['{0} edo {1}', '{0} edo {1}', '{0} edo {1}'],
  UNIT_END: ['{0} eta {1}', '{0} eta {1}', '{0} eta {1}']
};

/**
 * List formatting symbols for locale fa.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_fa = {
  AND_START: ['{0}،‏ {1}', '{0}،‏ {1}', '{0}،‏ {1}'],
  AND_TWO: ['{0} و {1}', '{0} و {1}', '{0}،‏ {1}'],
  AND_END: ['{0}، و {1}', '{0}، و {1}', '{0}،‏ {1}'],
  OR_TWO: ['{0} یا {1}', '{0} یا {1}', '{0} یا {1}'],
  OR_END: ['{0}، یا {1}', '{0}، یا {1}', '{0}، یا {1}'],
  UNIT_START: ['{0}،‏ {1}', '{0}،‏ {1}', '{0} {1}'],
  UNIT_TWO: ['{0} و {1}', '{0}،‏ {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}،‏ {1}', '{0}،‏ {1}', '{0} {1}'],
  UNIT_END: ['{0}، و {1}', '{0}، و {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale fi.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_fi = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} ja {1}', '{0} ja {1}', '{0} ja {1}'],
  OR_END: ['{0} tai {1}', '{0} tai {1}', '{0} tai {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} ja {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale fil.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_fil = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} at {1}', '{0} at {1}', '{0}, {1}'],
  AND_END: ['{0}, at {1}', '{0}, at {1}', '{0}, {1}'],
  OR_TWO: ['{0} o {1}', '{0} o {1}', '{0} o {1}'],
  OR_END: ['{0}, o {1}', '{0}, o {1}', '{0}, o {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale fr.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_fr = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} et {1}', '{0} et {1}', '{0}, {1}'],
  OR_END: ['{0} ou {1}', '{0} ou {1}', '{0} ou {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} et {1}', '{0} et {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale fr_CA.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_fr_CA = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} et {1}', '{0} et {1}', '{0}, {1}'],
  OR_END: ['{0} ou {1}', '{0} ou {1}', '{0} ou {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} et {1}', '{0} et {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale ga.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ga = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} agus {1}', '{0} agus {1}', '{0}, {1}'],
  OR_END: ['{0} nó {1}', '{0} nó {1}', '{0} nó {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} agus {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale gl.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_gl = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} e {1}', '{0} e {1}', '{0} e {1}'],
  OR_END: ['{0} ou {1}', '{0} ou {1}', '{0} ou {1}'],
  UNIT_END: ['{0} e {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale gsw.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_gsw = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} und {1}', '{0}, {1}', '{0}, {1}'],
  OR_END: ['{0}, or {1}', '{0}, or {1}', '{0}, or {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale gu.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_gu = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} અને {1}', '{0} અને {1}', '{0}, {1}'],
  OR_END: ['{0}, અથવા {1}', '{0}, અથવા {1}', '{0}, અથવા {1}'],
  UNIT_TWO: ['{0} અને {1}', '{0}, {1}', '{0}, {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale haw.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_haw = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  OR_END: ['{0}, or {1}', '{0}, or {1}', '{0}, or {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale he.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_he = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} ו{1}', '{0} ו{1}', '{0} ו{1}'],
  OR_END: ['{0} או {1}', '{0} או {1}', '{0} או {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_TWO: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} ו-{1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale hi.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_hi = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} और {1}', '{0} और {1}', '{0} और {1}'],
  AND_END: ['{0}, और {1}', '{0} और {1}', '{0} और {1}'],
  OR_TWO: ['{0} या {1}', '{0} या {1}', '{0} या {1}'],
  OR_END: ['{0} या {1}', '{0} या {1}', '{0} या {1}'],
  UNIT_TWO: ['{0} और {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, और {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale hr.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_hr = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}'],
  OR_END: ['{0} ili {1}', '{0} ili {1}', '{0} ili {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} i {1}', '{0} i {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale hu.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_hu = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} és {1}', '{0} és {1}', '{0} és {1}'],
  OR_END: ['{0} vagy {1}', '{0} vagy {1}', '{0} vagy {1}'],
  UNIT_END: ['{0} és {1}', '{0} és {1}', '{0} és {1}']
};

/**
 * List formatting symbols for locale hy.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_hy = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} և {1}', '{0} և {1}', '{0}, {1}'],
  OR_END: ['{0} կամ {1}', '{0} կամ {1}', '{0} կամ {1}'],
  UNIT_START: ['{0}, {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} և {1}', '{0} և {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale id.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_id = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} dan {1}', '{0} dan {1}', '{0}, {1}'],
  AND_END: ['{0}, dan {1}', '{0}, dan {1}', '{0}, {1}'],
  OR_TWO: ['{0} atau {1}', '{0} atau {1}', '{0} atau {1}'],
  OR_END: ['{0}, atau {1}', '{0}, atau {1}', '{0}, atau {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale in.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_in = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} dan {1}', '{0} dan {1}', '{0}, {1}'],
  AND_END: ['{0}, dan {1}', '{0}, dan {1}', '{0}, {1}'],
  OR_TWO: ['{0} atau {1}', '{0} atau {1}', '{0} atau {1}'],
  OR_END: ['{0}, atau {1}', '{0}, atau {1}', '{0}, atau {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale is.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_is = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} og {1}', '{0} og {1}', '{0}, {1}'],
  OR_END: ['{0} eða {1}', '{0} eða {1}', '{0} eða {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} og {1}', '{0} og {1}', '{0} og {1}']
};

/**
 * List formatting symbols for locale it.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_it = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} e {1}', '{0} e {1}', '{0} e {1}'],
  OR_END: ['{0} o {1}', '{0} o {1}', '{0} o {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} e {1}', '{0} e {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale iw.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_iw = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} ו{1}', '{0} ו{1}', '{0} ו{1}'],
  OR_END: ['{0} או {1}', '{0} או {1}', '{0} או {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_TWO: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} ו-{1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale ja.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ja = {
  AND_START: ['{0}、{1}', '{0}、{1}', '{0}、{1}'],
  AND_END: ['{0}、{1}', '{0}、{1}', '{0}、{1}'],
  OR_END: ['{0}、または{1}', '{0}、または{1}', '{0}、または{1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0}{1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0}{1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0}{1}']
};

/**
 * List formatting symbols for locale ka.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ka = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} და {1}', '{0} და {1}', '{0} და {1}'],
  OR_END: ['{0} ან {1}', '{0} ან {1}', '{0} ან {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale kk.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_kk = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} және {1}', '{0} және {1}', '{0} және {1}'],
  AND_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  OR_TWO: ['{0} не {1}', '{0} не {1}', '{0} не {1}'],
  OR_END: ['{0}, не болмаса {1}', '{0}, не болмаса {1}', '{0}, не болмаса {1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale km.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_km = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} និង​{1}', '{0} និង {1}', '{0}, {1}'],
  AND_END: ['{0} និង {1}', '{0} និង {1}', '{0}, {1}'],
  OR_TWO: ['{0} ឬ {1}', '{0} ឬ {1}', '{0} ឬ {1}'],
  OR_END: ['{0} ឬ {1}', '{0} ឬ {1}', '{0} ឬ {1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale kn.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_kn = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} ಮತ್ತು {1}', '{0} ಮತ್ತು {1}', '{0}, {1}'],
  AND_END: ['{0}, ಮತ್ತು {1}', '{0}, ಮತ್ತು {1}', '{0}, {1}'],
  OR_TWO: ['{0} ಅಥವಾ {1}', '{0} ಅಥವಾ {1}', '{0} ಅಥವಾ {1}'],
  OR_END: ['{0}, ಅಥವಾ {1}', '{0}, ಅಥವಾ {1}', '{0}, ಅಥವಾ {1}'],
  UNIT_TWO: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale ko.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ko = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} 및 {1}', '{0} 및 {1}', '{0} 및 {1}'],
  OR_END: ['{0} 또는 {1}', '{0} 또는 {1}', '{0} 또는 {1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale ky.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ky = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} жана {1}', '{0} жана {1}', '{0} жана {1}'],
  OR_END: ['{0} же {1}', '{0} же {1}', '{0} же {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale ln.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ln = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  OR_END: ['{0}, or {1}', '{0}, or {1}', '{0}, or {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale lo.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_lo = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} ແລະ {1}', '{0} ແລະ {1}', '{0} ແລະ {1}'],
  AND_END: ['{0}, {1}', '{0} ແລະ {1}', '{0}, {1}'],
  OR_TWO: ['{0} ຫຼື {1}', '{0} ຫຼື {1}', '{0} ຫຼື {1}'],
  OR_END: ['{0} ຫຼື {1}', '{0} ຫຼື {1}', '{0} ຫຼື {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale lt.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_lt = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} ir {1}', '{0} ir {1}', '{0} ir {1}'],
  OR_END: ['{0} ar {1}', '{0} ar {1}', '{0} ar {1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} ir {1}', '{0} {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale lv.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_lv = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} un {1}', '{0} un {1}', '{0} un {1}'],
  OR_END: ['{0} vai {1}', '{0} vai {1}', '{0} vai {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} un {1}', '{0} un {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale mk.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_mk = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} и {1}', '{0} и {1}', '{0} и {1}'],
  OR_END: ['{0} или {1}', '{0} или {1}', '{0} или {1}'],
  UNIT_END: ['{0} и {1}', '{0} и {1}', '{0} и {1}']
};

/**
 * List formatting symbols for locale ml.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ml = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} കൂടാതെ {1}', '{0} കൂടാതെ {1}', '{0}, {1} എന്നിവ'],
  AND_END: ['{0}, {1} എന്നിവ', '{0}, {1} എന്നിവ', '{0}, {1} എന്നിവ'],
  OR_TWO: ['{0} അല്ലെങ്കിൽ {1}', '{0} അല്ലെങ്കിൽ {1}', '{0} അല്ലെങ്കിൽ {1}'],
  OR_END: ['{0}, അല്ലെങ്കിൽ {1}', '{0}, അല്ലെങ്കിൽ {1}', '{0}, അല്ലെങ്കിൽ {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_TWO: ['{0} കൂടാതെ {1}', '{0}, {1}', '{0}, {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale mn.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_mn = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  OR_END: ['{0}, {1} зэргийн аль нэг', '{0}, {1} зэргийн аль нэг', '{0}, {1} зэргийн аль нэг'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale mo.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_mo = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} și {1}', '{0} și {1}', '{0}, {1}'],
  OR_END: ['{0} sau {1}', '{0} sau {1}', '{0} sau {1}'],
  UNIT_TWO: ['{0} și {1}', '{0}, {1}', '{0}, {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale mr.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_mr = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} आणि {1}', '{0} आणि {1}', '{0} आणि {1}'],
  OR_END: ['{0}, किंवा {1}', '{0}, किंवा {1}', '{0}, किंवा {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale ms.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ms = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} dan {1}', '{0} dan {1}', '{0}, {1}'],
  OR_END: ['{0}, atau {1}', '{0}, atau {1}', '{0}, atau {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0} dan {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale mt.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_mt = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} u {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0}, u {1}', '{0}, {1}', '{0}, {1}'],
  OR_TWO: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  OR_END: ['{0}, or {1}', '{0}, or {1}', '{0}, or {1}'],
  UNIT_TWO: ['{0} u {1}', '{0} u {1}', '{0}, {1}'],
  UNIT_END: ['{0}, u {1}', '{0}, u {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale my.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_my = {
  AND_START: ['{0} - {1}', '{0} - {1}', '{0} - {1}'],
  AND_END: ['{0}နှင့် {1}', '{0}နှင့် {1}', '{0}နှင့် {1}'],
  OR_END: ['{0} သို့မဟုတ် {1}', '{0} သို့မဟုတ် {1}', '{0} သို့မဟုတ် {1}'],
  UNIT_START: ['{0}- {1}', '{0}- {1}', '{0} {1}'],
  UNIT_TWO: ['{0}နှင့်{1}', '{0}နှင့် {1}', '{0}နှင့် {1}'],
  UNIT_MIDDLE: ['{0}- {1}', '{0}- {1}', '{0} {1}'],
  UNIT_END: ['{0}နှင့် {1}', '{0}နှင့် {1}', '{0}နှင့် {1}']
};

/**
 * List formatting symbols for locale nb.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_nb = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} og {1}', '{0} og {1}', '{0} og {1}'],
  OR_END: ['{0} eller {1}', '{0} eller {1}', '{0} eller {1}'],
  UNIT_END: ['{0} og {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale ne.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ne = {
  AND_START: ['{0},{1}', '{0},{1}', '{0},{1}'],
  AND_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} र {1}', '{0} र {1}', '{0}, {1}'],
  OR_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  OR_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  OR_END: ['{0}, वा {1}', '{0}, वा {1}', '{0}, वा {1}'],
  UNIT_START: ['{0},{1}', '{0},{1}', '{0} {1}'],
  UNIT_TWO: ['{0},{1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0}{1}'],
  UNIT_END: ['{0},{1}', '{0},{1}', '{0} {1}']
};

/**
 * List formatting symbols for locale nl.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_nl = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} en {1}', '{0} en {1}', '{0} en {1}'],
  OR_END: ['{0} of {1}', '{0} of {1}', '{0} of {1}'],
  UNIT_END: ['{0} en {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale no.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_no = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} og {1}', '{0} og {1}', '{0} og {1}'],
  OR_END: ['{0} eller {1}', '{0} eller {1}', '{0} eller {1}'],
  UNIT_END: ['{0} og {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale no_NO.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_no_NO = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} og {1}', '{0} og {1}', '{0} og {1}'],
  OR_END: ['{0} eller {1}', '{0} eller {1}', '{0} eller {1}'],
  UNIT_END: ['{0} og {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale or.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_or = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} ଓ {1}', '{0} ଓ {1}', '{0} ଓ {1}'],
  AND_END: ['{0}, ଓ {1}', '{0}, ଓ {1}', '{0}, ଓ {1}'],
  OR_TWO: ['{0} କିମ୍ବା {1}', '{0} କିମ୍ବା {1}', '{0} କିମ୍ବା {1}'],
  OR_END: ['{0} କିମ୍ବା {1}', '{0} କିମ୍ବା {1}', '{0} କିମ୍ବା {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale pa.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_pa = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} ਅਤੇ {1}', '{0} ਅਤੇ {1}', '{0}, {1}'],
  OR_END: ['{0} ਜਾਂ {1}', '{0} ਜਾਂ {1}', '{0} ਜਾਂ {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale pl.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_pl = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}'],
  OR_END: ['{0} lub {1}', '{0} lub {1}', '{0} lub {1}'],
  UNIT_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}']
};

/**
 * List formatting symbols for locale pt.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_pt = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} e {1}', '{0} e {1}', '{0}, {1}'],
  OR_END: ['{0} ou {1}', '{0} ou {1}', '{0} ou {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} e {1}', '{0} e {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale pt_BR.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_pt_BR = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} e {1}', '{0} e {1}', '{0}, {1}'],
  OR_END: ['{0} ou {1}', '{0} ou {1}', '{0} ou {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0} e {1}', '{0} e {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale pt_PT.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_pt_PT = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} e {1}', '{0} e {1}', '{0}, {1}'],
  OR_END: ['{0} ou {1}', '{0} ou {1}', '{0} ou {1}'],
  UNIT_END: ['{0} e {1}', '{0} e {1}', '{0} e {1}']
};

/**
 * List formatting symbols for locale ro.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ro = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} și {1}', '{0} și {1}', '{0}, {1}'],
  OR_END: ['{0} sau {1}', '{0} sau {1}', '{0} sau {1}'],
  UNIT_TWO: ['{0} și {1}', '{0}, {1}', '{0}, {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale ru.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ru = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} и {1}', '{0} и {1}', '{0}, {1}'],
  OR_END: ['{0} или {1}', '{0} или {1}', '{0} или {1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale sh.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_sh = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}'],
  OR_END: ['{0} ili {1}', '{0} ili {1}', '{0} ili {1}'],
  UNIT_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}']
};

/**
 * List formatting symbols for locale si.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_si = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} සහ {1}', '{0} සහ {1}', '{0} සහ {1}'],
  AND_END: ['{0}, සහ {1}', '{0}, සහ {1}', '{0}, සහ {1}'],
  OR_TWO: ['{0} හෝ {1}', '{0} හෝ {1}', '{0} හෝ {1}'],
  OR_END: ['{0}, හෝ {1}', '{0}, හෝ {1}', '{0}, හෝ {1}'],
  UNIT_TWO: ['{0} සහ {1}', '{0} සහ {1}', '{0} සහ {1}'],
  UNIT_END: ['{0}, සහ {1}', '{0}, සහ {1}', '{0}, සහ {1}']
};

/**
 * List formatting symbols for locale sk.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_sk = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} a {1}', '{0} a {1}', '{0} a {1}'],
  AND_END: ['{0} a {1}', '{0} a {1}', '{0} a {1}'],
  OR_TWO: ['{0} alebo {1}', '{0} alebo {1}', '{0} alebo {1}'],
  OR_END: ['{0} alebo {1}', '{0} alebo {1}', '{0} alebo {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale sl.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_sl = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} in {1}', '{0} in {1}', '{0} in {1}'],
  OR_END: ['{0} ali {1}', '{0} ali {1}', '{0} ali {1}'],
  UNIT_END: ['{0} in {1}', '{0} in {1}', '{0} in {1}']
};

/**
 * List formatting symbols for locale sq.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_sq = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} dhe {1}', '{0} dhe {1}', '{0} dhe {1}'],
  OR_END: ['{0} ose {1}', '{0} ose {1}', '{0} ose {1}'],
  UNIT_END: ['{0} e {1}', '{0} e {1}', '{0} e {1}']
};

/**
 * List formatting symbols for locale sr.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_sr = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} и {1}', '{0} и {1}', '{0} и {1}'],
  OR_END: ['{0} или {1}', '{0} или {1}', '{0} или {1}'],
  UNIT_END: ['{0} и {1}', '{0} и {1}', '{0} и {1}']
};

/**
 * List formatting symbols for locale sr_Latn.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_sr_Latn = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}'],
  OR_END: ['{0} ili {1}', '{0} ili {1}', '{0} ili {1}'],
  UNIT_END: ['{0} i {1}', '{0} i {1}', '{0} i {1}']
};

/**
 * List formatting symbols for locale sv.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_sv = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} och {1}', '{0} och {1}', '{0}, {1}'],
  OR_END: ['{0} eller {1}', '{0} eller {1}', '{0} eller {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale sw.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_sw = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} na {1}', '{0} na {1}', '{0}, {1}'],
  AND_END: ['{0} na {1}', '{0} na {1}', '{0} na {1}'],
  OR_TWO: ['{0} au {1}', '{0} au {1}', '{0} au {1}'],
  OR_END: ['{0} au {1}', '{0} au {1}', '{0} au {1}'],
  UNIT_END: ['{0} na {1}', '{0} na {1}', '{0} na {1}']
};

/**
 * List formatting symbols for locale ta.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ta = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} மற்றும் {1}', '{0} மற்றும் {1}', '{0} மற்றும் {1}'],
  OR_END: ['{0} அல்லது {1}', '{0} அல்லது {1}', '{0} அல்லது {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale te.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_te = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} మరియు {1}', '{0} మరియు {1}', '{0}, {1}'],
  OR_END: ['{0} లేదా {1}', '{0} లేదా {1}', '{0} లేదా {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0}, {1}']
};

/**
 * List formatting symbols for locale th.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_th = {
  AND_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  AND_TWO: ['{0}และ{1}', '{0}และ{1}', '{0}และ{1}'],
  AND_END: ['{0} และ{1}', '{0} และ{1}', '{0} และ{1}'],
  OR_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  OR_TWO: ['{0} หรือ {1}', '{0} หรือ {1}', '{0} หรือ {1}'],
  OR_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  OR_END: ['{0} หรือ {1}', '{0} หรือ {1}', '{0} หรือ {1}'],
  UNIT_TWO: ['{0} และ {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} และ {1}', '{0} และ {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale tl.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_tl = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} at {1}', '{0} at {1}', '{0}, {1}'],
  AND_END: ['{0}, at {1}', '{0}, at {1}', '{0}, {1}'],
  OR_TWO: ['{0} o {1}', '{0} o {1}', '{0} o {1}'],
  OR_END: ['{0}, o {1}', '{0}, o {1}', '{0}, o {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale tr.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_tr = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} ve {1}', '{0} ve {1}', '{0}, {1}'],
  OR_END: ['{0} veya {1}', '{0} veya {1}', '{0} veya {1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale uk.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_uk = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} і {1}', '{0} і {1}', '{0}, {1}'],
  OR_END: ['{0} або {1}', '{0} або {1}', '{0} або {1}'],
  UNIT_END: ['{0} і {1}', '{0} і {1}', '{0} і {1}']
};

/**
 * List formatting symbols for locale ur.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_ur = {
  AND_START: ['{0}، {1}', '{0}، {1}', '{0}، {1}'],
  AND_TWO: ['{0} اور {1}', '{0} اور {1}', '{0}، {1}'],
  AND_END: ['{0}، اور {1}', '{0}، اور {1}', '{0}، {1}'],
  OR_TWO: ['{0} یا {1}', '{0} یا {1}', '{0} یا {1}'],
  OR_END: ['{0}، یا {1}', '{0}، یا {1}', '{0}، یا {1}'],
  UNIT_START: ['{0}, {1}', '{0}، {1}', '{0}، {1}'],
  UNIT_TWO: ['{0}، {1}', '{0} اور {1}', '{0} اور {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}، {1}', '{0}، {1}'],
  UNIT_END: ['{0}، اور {1}', '{0}، اور {1}', '{0}، اور {1}']
};

/**
 * List formatting symbols for locale uz.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_uz = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} va {1}', '{0} va {1}', '{0}, {1}'],
  OR_END: ['{0} yoki {1}', '{0} yoki {1}', '{0} yoki {1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0} {1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale vi.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_vi = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_END: ['{0} và {1}', '{0} và {1}', '{0}, {1}'],
  OR_END: ['{0} hoặc {1}', '{0} hoặc {1}', '{0} hoặc {1}'],
  UNIT_START: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_MIDDLE: ['{0}, {1}', '{0}, {1}', '{0} {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * List formatting symbols for locale zh.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_zh = {
  AND_START: ['{0}、{1}', '{0}、{1}', '{0}、{1}'],
  AND_END: ['{0}和{1}', '{0}和{1}', '{0}、{1}'],
  OR_END: ['{0}或{1}', '{0}或{1}', '{0}或{1}'],
  UNIT_START: ['{0}{1}', '{0}{1}', '{0}{1}'],
  UNIT_MIDDLE: ['{0}{1}', '{0}{1}', '{0}{1}'],
  UNIT_END: ['{0}{1}', '{0}{1}', '{0}{1}']
};

/**
 * List formatting symbols for locale zh_CN.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_zh_CN = {
  AND_START: ['{0}、{1}', '{0}、{1}', '{0}、{1}'],
  AND_END: ['{0}和{1}', '{0}和{1}', '{0}、{1}'],
  OR_END: ['{0}或{1}', '{0}或{1}', '{0}或{1}'],
  UNIT_START: ['{0}{1}', '{0}{1}', '{0}{1}'],
  UNIT_MIDDLE: ['{0}{1}', '{0}{1}', '{0}{1}'],
  UNIT_END: ['{0}{1}', '{0}{1}', '{0}{1}']
};

/**
 * List formatting symbols for locale zh_HK.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_zh_HK = {
  AND_START: ['{0}、{1}', '{0}、{1}', '{0}、{1}'],
  AND_END: ['{0}及{1}', '{0}及{1}', '{0}及{1}'],
  OR_END: ['{0}或{1}', '{0}或{1}', '{0}或{1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0}{1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0}{1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0}{1}']
};

/**
 * List formatting symbols for locale zh_TW.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_zh_TW = {
  AND_START: ['{0}、{1}', '{0}、{1}', '{0}、{1}'],
  AND_END: ['{0}和{1}', '{0}和{1}', '{0}和{1}'],
  OR_END: ['{0}或{1}', '{0}或{1}', '{0}或{1}'],
  UNIT_START: ['{0} {1}', '{0} {1}', '{0}{1}'],
  UNIT_MIDDLE: ['{0} {1}', '{0} {1}', '{0}{1}'],
  UNIT_END: ['{0} {1}', '{0} {1}', '{0}{1}']
};

/**
 * List formatting symbols for locale zu.
 * @const ListFormatSymbols
 */
export let ListFormatSymbols_zu = {
  AND_START: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  AND_TWO: ['{0} ne-{1}', '{0} ne-{1}', '{0}, {1}'],
  AND_END: ['{0}, ne-{1}', '{0}, ne-{1}', '{0}, {1}'],
  OR_TWO: ['{0} or {1}', '{0} or {1}', '{0} or {1}'],
  OR_END: ['{0}, or {1}', '{0}, or {1}', '{0}, or {1}'],
  UNIT_TWO: ['{0}, {1}', '{0}, {1}', '{0}, {1}'],
  UNIT_END: ['{0}, {1}', '{0}, {1}', '{0} {1}']
};

/**
 * Default value, in case nothing else matches
 * @type  {!ListFormatSymbols}
 */
let defaultSymbols = ListFormatSymbols_en;


/**
 * Returns the default ListFormatSymbols
 * @return {!ListFormatSymbols}
 */
export function getListFormatSymbols() {
  return defaultSymbols;
};

/**
 * Sets the default ListFormatSymbols
 * @param {!ListFormatSymbols} symbols
 */
export function setListFormatSymbols(symbols) {
  defaultSymbols = symbols;
};

/**
 * Selecting symbols by locale.
 */
switch (goog.LOCALE) {
  case 'af':
    defaultSymbols = ListFormatSymbols_af;
    break;
  case 'am':
    defaultSymbols = ListFormatSymbols_am;
    break;
  case 'ar':
    defaultSymbols = ListFormatSymbols_ar;
    break;
  case 'ar_DZ':
  case 'ar-DZ':
    defaultSymbols = ListFormatSymbols_ar_DZ;
    break;
  case 'ar_EG':
  case 'ar-EG':
    defaultSymbols = ListFormatSymbols_ar_EG;
    break;
  case 'az':
    defaultSymbols = ListFormatSymbols_az;
    break;
  case 'be':
    defaultSymbols = ListFormatSymbols_be;
    break;
  case 'bg':
    defaultSymbols = ListFormatSymbols_bg;
    break;
  case 'bn':
    defaultSymbols = ListFormatSymbols_bn;
    break;
  case 'br':
    defaultSymbols = ListFormatSymbols_br;
    break;
  case 'bs':
    defaultSymbols = ListFormatSymbols_bs;
    break;
  case 'ca':
    defaultSymbols = ListFormatSymbols_ca;
    break;
  case 'chr':
    defaultSymbols = ListFormatSymbols_chr;
    break;
  case 'cs':
    defaultSymbols = ListFormatSymbols_cs;
    break;
  case 'cy':
    defaultSymbols = ListFormatSymbols_cy;
    break;
  case 'da':
    defaultSymbols = ListFormatSymbols_da;
    break;
  case 'de':
    defaultSymbols = ListFormatSymbols_de;
    break;
  case 'de_AT':
  case 'de-AT':
    defaultSymbols = ListFormatSymbols_de_AT;
    break;
  case 'de_CH':
  case 'de-CH':
    defaultSymbols = ListFormatSymbols_de_CH;
    break;
  case 'el':
    defaultSymbols = ListFormatSymbols_el;
    break;
  case 'en':
    defaultSymbols = ListFormatSymbols_en;
    break;
  case 'en_AU':
  case 'en-AU':
    defaultSymbols = ListFormatSymbols_en_AU;
    break;
  case 'en_CA':
  case 'en-CA':
    defaultSymbols = ListFormatSymbols_en_CA;
    break;
  case 'en_GB':
  case 'en-GB':
    defaultSymbols = ListFormatSymbols_en_GB;
    break;
  case 'en_IE':
  case 'en-IE':
    defaultSymbols = ListFormatSymbols_en_IE;
    break;
  case 'en_IN':
  case 'en-IN':
    defaultSymbols = ListFormatSymbols_en_IN;
    break;
  case 'en_SG':
  case 'en-SG':
    defaultSymbols = ListFormatSymbols_en_SG;
    break;
  case 'en_US':
  case 'en-US':
    defaultSymbols = ListFormatSymbols_en_US;
    break;
  case 'en_ZA':
  case 'en-ZA':
    defaultSymbols = ListFormatSymbols_en_ZA;
    break;
  case 'es':
    defaultSymbols = ListFormatSymbols_es;
    break;
  case 'es_419':
  case 'es-419':
    defaultSymbols = ListFormatSymbols_es_419;
    break;
  case 'es_ES':
  case 'es-ES':
    defaultSymbols = ListFormatSymbols_es_ES;
    break;
  case 'es_MX':
  case 'es-MX':
    defaultSymbols = ListFormatSymbols_es_MX;
    break;
  case 'es_US':
  case 'es-US':
    defaultSymbols = ListFormatSymbols_es_US;
    break;
  case 'et':
    defaultSymbols = ListFormatSymbols_et;
    break;
  case 'eu':
    defaultSymbols = ListFormatSymbols_eu;
    break;
  case 'fa':
    defaultSymbols = ListFormatSymbols_fa;
    break;
  case 'fi':
    defaultSymbols = ListFormatSymbols_fi;
    break;
  case 'fil':
    defaultSymbols = ListFormatSymbols_fil;
    break;
  case 'fr':
    defaultSymbols = ListFormatSymbols_fr;
    break;
  case 'fr_CA':
  case 'fr-CA':
    defaultSymbols = ListFormatSymbols_fr_CA;
    break;
  case 'ga':
    defaultSymbols = ListFormatSymbols_ga;
    break;
  case 'gl':
    defaultSymbols = ListFormatSymbols_gl;
    break;
  case 'gsw':
    defaultSymbols = ListFormatSymbols_gsw;
    break;
  case 'gu':
    defaultSymbols = ListFormatSymbols_gu;
    break;
  case 'haw':
    defaultSymbols = ListFormatSymbols_haw;
    break;
  case 'he':
    defaultSymbols = ListFormatSymbols_he;
    break;
  case 'hi':
    defaultSymbols = ListFormatSymbols_hi;
    break;
  case 'hr':
    defaultSymbols = ListFormatSymbols_hr;
    break;
  case 'hu':
    defaultSymbols = ListFormatSymbols_hu;
    break;
  case 'hy':
    defaultSymbols = ListFormatSymbols_hy;
    break;
  case 'id':
    defaultSymbols = ListFormatSymbols_id;
    break;
  case 'in':
    defaultSymbols = ListFormatSymbols_in;
    break;
  case 'is':
    defaultSymbols = ListFormatSymbols_is;
    break;
  case 'it':
    defaultSymbols = ListFormatSymbols_it;
    break;
  case 'iw':
    defaultSymbols = ListFormatSymbols_iw;
    break;
  case 'ja':
    defaultSymbols = ListFormatSymbols_ja;
    break;
  case 'ka':
    defaultSymbols = ListFormatSymbols_ka;
    break;
  case 'kk':
    defaultSymbols = ListFormatSymbols_kk;
    break;
  case 'km':
    defaultSymbols = ListFormatSymbols_km;
    break;
  case 'kn':
    defaultSymbols = ListFormatSymbols_kn;
    break;
  case 'ko':
    defaultSymbols = ListFormatSymbols_ko;
    break;
  case 'ky':
    defaultSymbols = ListFormatSymbols_ky;
    break;
  case 'ln':
    defaultSymbols = ListFormatSymbols_ln;
    break;
  case 'lo':
    defaultSymbols = ListFormatSymbols_lo;
    break;
  case 'lt':
    defaultSymbols = ListFormatSymbols_lt;
    break;
  case 'lv':
    defaultSymbols = ListFormatSymbols_lv;
    break;
  case 'mk':
    defaultSymbols = ListFormatSymbols_mk;
    break;
  case 'ml':
    defaultSymbols = ListFormatSymbols_ml;
    break;
  case 'mn':
    defaultSymbols = ListFormatSymbols_mn;
    break;
  case 'mo':
    defaultSymbols = ListFormatSymbols_mo;
    break;
  case 'mr':
    defaultSymbols = ListFormatSymbols_mr;
    break;
  case 'ms':
    defaultSymbols = ListFormatSymbols_ms;
    break;
  case 'mt':
    defaultSymbols = ListFormatSymbols_mt;
    break;
  case 'my':
    defaultSymbols = ListFormatSymbols_my;
    break;
  case 'nb':
    defaultSymbols = ListFormatSymbols_nb;
    break;
  case 'ne':
    defaultSymbols = ListFormatSymbols_ne;
    break;
  case 'nl':
    defaultSymbols = ListFormatSymbols_nl;
    break;
  case 'no':
    defaultSymbols = ListFormatSymbols_no;
    break;
  case 'no_NO':
  case 'no-NO':
    defaultSymbols = ListFormatSymbols_no_NO;
    break;
  case 'or':
    defaultSymbols = ListFormatSymbols_or;
    break;
  case 'pa':
    defaultSymbols = ListFormatSymbols_pa;
    break;
  case 'pl':
    defaultSymbols = ListFormatSymbols_pl;
    break;
  case 'pt':
    defaultSymbols = ListFormatSymbols_pt;
    break;
  case 'pt_BR':
  case 'pt-BR':
    defaultSymbols = ListFormatSymbols_pt_BR;
    break;
  case 'pt_PT':
  case 'pt-PT':
    defaultSymbols = ListFormatSymbols_pt_PT;
    break;
  case 'ro':
    defaultSymbols = ListFormatSymbols_ro;
    break;
  case 'ru':
    defaultSymbols = ListFormatSymbols_ru;
    break;
  case 'sh':
    defaultSymbols = ListFormatSymbols_sh;
    break;
  case 'si':
    defaultSymbols = ListFormatSymbols_si;
    break;
  case 'sk':
    defaultSymbols = ListFormatSymbols_sk;
    break;
  case 'sl':
    defaultSymbols = ListFormatSymbols_sl;
    break;
  case 'sq':
    defaultSymbols = ListFormatSymbols_sq;
    break;
  case 'sr':
    defaultSymbols = ListFormatSymbols_sr;
    break;
  case 'sr_Latn':
  case 'sr-Latn':
    defaultSymbols = ListFormatSymbols_sr_Latn;
    break;
  case 'sv':
    defaultSymbols = ListFormatSymbols_sv;
    break;
  case 'sw':
    defaultSymbols = ListFormatSymbols_sw;
    break;
  case 'ta':
    defaultSymbols = ListFormatSymbols_ta;
    break;
  case 'te':
    defaultSymbols = ListFormatSymbols_te;
    break;
  case 'th':
    defaultSymbols = ListFormatSymbols_th;
    break;
  case 'tl':
    defaultSymbols = ListFormatSymbols_tl;
    break;
  case 'tr':
    defaultSymbols = ListFormatSymbols_tr;
    break;
  case 'uk':
    defaultSymbols = ListFormatSymbols_uk;
    break;
  case 'ur':
    defaultSymbols = ListFormatSymbols_ur;
    break;
  case 'uz':
    defaultSymbols = ListFormatSymbols_uz;
    break;
  case 'vi':
    defaultSymbols = ListFormatSymbols_vi;
    break;
  case 'zh':
    defaultSymbols = ListFormatSymbols_zh;
    break;
  case 'zh_CN':
  case 'zh-CN':
    defaultSymbols = ListFormatSymbols_zh_CN;
    break;
  case 'zh_HK':
  case 'zh-HK':
    defaultSymbols = ListFormatSymbols_zh_HK;
    break;
  case 'zh_TW':
  case 'zh-TW':
    defaultSymbols = ListFormatSymbols_zh_TW;
    break;
  case 'zu':
    defaultSymbols = ListFormatSymbols_zu;
    break;
}
