/**
 * @license
 * Copyright The Closure Library Authors.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @fileoverview Factory class to create a rich autocomplete that will match
 * from an array of data provided via ajax.  The server returns a complex data
 * structure that is used with client-side javascript functions to render the
 * results.
 *
 * The server sends a list of the form:
 *   [["type1", {...}, {...}, ...], ["type2", {...}, {...}, ...], ...]
 * The first element of each sublist is a string designating the type of the
 * hashes in the sublist, each of which represents one match.  The type string
 * must be the name of a function(item) which converts the hash into a rich
 * row that contains both a render(node, token) and a select(target) method.
 * The render method is called by the renderer when rendering the rich row,
 * and the select method is called by the RichInputHandler when the rich row is
 * selected.
 *
 * @see ../../demos/autocompleterichremote.html
 */

import { AutoComplete } from './autocomplete.js';

import { Remote } from './remote.js';
import { Renderer } from './renderer.js';
import { RichInputHandler } from './richinputhandler.js';
import { RichRemoteArrayMatcher } from './richremotearraymatcher.js';



/**
 * Factory class to create a rich autocomplete widget that autocompletes an
 * inputbox or textarea from data provided via ajax.  The server returns a
 * complex data structure that is used with client-side javascript functions to
 * render the results.
 *
 * @param {string} url The Uri which generates the auto complete matches.
 * @param {Element} input Input element or text area.
 * @param {boolean=} opt_multi Whether to allow multiple entries; defaults
 *     to false.
 * @param {boolean=} opt_useSimilar Whether to use similar matches; e.g.
 *     "gost" => "ghost".
 * @constructor
 * @extends {Remote}
 */
export function RichRemote(url, input, opt_multi, opt_useSimilar) {
 // Create a custom renderer that renders rich rows.  The renderer calls
 // row.render(node, token) for each row.
 var customRenderer = {};
 customRenderer.renderRow = function(row, token, node) {
  return row.data.render(node, token);
 };

 /**
   * A standard renderer that uses a custom row renderer to display the
   * rich rows generated by this autocomplete widget.
   * @type {Renderer}
   * @private
   */
 var renderer = new Renderer(null, customRenderer);

 /**
    * A remote matcher that parses rich results returned by the server.
    * @type {RichRemoteArrayMatcher}
    * @private
    */
 var matcher = new RichRemoteArrayMatcher(url, !opt_useSimilar);

 /**
   * An input handler that calls select on a row when it is selected.
   * @type {RichInputHandler}
   * @private
   */
 var inputhandler =
     new RichInputHandler(null, null, !!opt_multi, 300);

 // Create the widget and connect it to the input handler.
 AutoComplete.call(this, matcher, renderer, inputhandler);
 inputhandler.attachAutoComplete(this);
 inputhandler.attachInputs(input);
}
goog.inherits(RichRemote, Remote);


/**
 * Set the filter that is called before the array matches are returned.
 * @param {Function} rowFilter A function(rows) that returns an array of rows as
 *     a subset of the rows input array.
 * @suppress {strictMissingProperties} Added to tighten compiler checks
 */
RichRemote.prototype.setRowFilter = function(rowFilter) {
 this.matcher_.setRowFilter(rowFilter);
};


/**
 * Sets the function building the rows.
 * @param {RichRemoteArrayMatcher.RowBuilder} rowBuilder
 *     A function(type, response) converting the type and the server response to
 *     an object with two methods: render(node, token) and select(target).
 * @suppress {strictMissingProperties} Added to tighten compiler checks
 */
RichRemote.prototype.setRowBuilder = function(rowBuilder) {
 this.matcher_.setRowBuilder(rowBuilder);
};
